This is the project for the ShapeAI bootcamp..
The aim of this project is to determine the species of a flower based on some measurements given..
A basic ML model is being used here, with the concept of k-nearest neighbours. 

Importing the important libraries required for this project..


In [30]:
import pandas as pd
import numpy as np

Now, I am importing the ML framework..

In [5]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

Printing the keys of the dataset..

In [7]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))


Keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


DESCR is a key which stores a short description of the dataset.
Printing a value of DESCR..

In [9]:
print(iris_dataset['DESCR'][:192]+"\n....")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pr
....


target_names is the key which stores the specie-names of the flowers..
i.e. 'setosa','versicolor','virginica'.....
Printing target_names.. 

In [10]:
print("Target Names: {}".format(iris_dataset['target_names']))

Target Names: ['setosa' 'versicolor' 'virginica']


feature_names containing strings explaining features of the flower..
Printing feature_names...

In [11]:
print("Feature Names: \n{}".format(iris_dataset['feature_names']))

Feature Names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Printing type of data

In [12]:
print("Type of data:{}".format(type(iris_dataset['data'])))

Type of data:<class 'numpy.ndarray'>


Shape returns the number of rows and coloumns for a 2D array.
Printing shape....

In [13]:
print("Shape of data:{}".format(iris_dataset['data'].shape))

Shape of data:(150, 4)


Printing the first five rows of the nd-array using slicing operator..

In [14]:
print("First five rows of data:\n{}".format(iris_dataset['data'][:5]))

First five rows of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Printing the type and shape of target...

In [15]:
print("Type of target:{}".format(type(iris_dataset['target'])))
print("Shape of target:{}".format(iris_dataset['target'].shape))

Type of target:<class 'numpy.ndarray'>
Shape of target:(150,)


Now, printing the target..

In [16]:
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


A function will be imported to split the rows and re-arrange them for better efficiency..
It helps for training and testing data, in order to increase accuracy...
Random state will be assigned to 0 

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

Printing the shape of the above defined data..

In [19]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


Now, the code for the ML model will begin..
Concept being used- K-nearest neighbours...

In [20]:
from sklearn.neighbors import KNeighborsClassifier

Training the model on training data...

In [24]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Start of making predictions..

In [31]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


knn here is an object and I will make a prediction by calling predict method using knn object...

In [32]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predictted target name: {}".format(iris_dataset['target_names'][prediction]))

Prediction: [0]
Predictted target name: ['setosa']


Start of Evaluation of model...


In [33]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))


Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


Depicting the accuracy of the model via mean..


In [34]:
print("Test set score: {}".format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158


End of Project...
Thank you ShapeAI for this wonderful bootcamp..